In [106]:
import pandas as pd
import numpy as np

In [107]:
true= pd.read_csv('True.csv')

In [108]:
fake= pd.read_csv('Fake.csv')

In [109]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [110]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [111]:
true['label']=1

In [112]:
fake['label']=0

In [113]:
true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [114]:
news=pd.concat([fake,true],axis=0)

In [115]:
news.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [116]:
news.tail()

,title,text,subject,date,label
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [117]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [118]:
news=news.drop(['title','subject','date'], axis=1)

In [119]:
news.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [120]:
news=news.sample(frac=1)

In [121]:
news.head()

                                                    text  label
15175  There s always another side that s usually bei...      0
9788   WINSTON-SALEM, N.C. (Reuters) - Civil rights g...      1
16873  When Loretta Lynch was confirmed as the new Di...      0
6361   NEW YORK (Reuters) - French far-right presiden...      1
2165   (Reuters) - Negotiators from Canada, Mexico an...      1

In [122]:
news.reset_index(inplace=True)

In [123]:
news.head()

   index                                               text  label
0  15175  There s always another side that s usually bei...      0
1   9788  WINSTON-SALEM, N.C. (Reuters) - Civil rights g...      1
2  16873  When Loretta Lynch was confirmed as the new Di...      0
3   6361  NEW YORK (Reuters) - French far-right presiden...      1
4   2165  (Reuters) - Negotiators from Canada, Mexico an...      1

In [124]:
news.drop(['index'],axis=1,inplace=True)

In [125]:
news.head()

                                                text  label
0  There s always another side that s usually bei...      0
1  WINSTON-SALEM, N.C. (Reuters) - Civil rights g...      1
2  When Loretta Lynch was confirmed as the new Di...      0
3  NEW YORK (Reuters) - French far-right presiden...      1
4  (Reuters) - Negotiators from Canada, Mexico an...      1

In [126]:
import re

In [127]:
def wordopt(text):
  text=text.lower()

  text=re.sub(r'https?://\S+|www\.\S+','',text)

  text=re.sub(r'<.*?>','',text)

  text=re.sub(r'[^\w\s]','',text)

  text=re.sub(r'\d','',text)

  text=re.sub(r'\n','',text)

  return text

In [128]:
news['text']=news['text'].apply(wordopt)

In [129]:
news['text']

0        there s always another side that s usually bei...
1        winstonsalem nc reuters  civil rights groups a...
2        when loretta lynch was confirmed as the new di...
3        new york reuters  french farright presidential...
4        reuters  negotiators from canada mexico and th...
                               ...
44893    brasilia reuters  brazil s lower house of cong...
44894    mexico city reuters  tears flowed at our lady ...
44895    washington reuters  the white house on friday ...
44896    there has been a consistent thread in zionism ...
44897    no word yet on plans to defund state departmen...
Name: text, Length: 44898, dtype: object

In [130]:
x=news['text']
y=news['label']

In [131]:
x

0        there s always another side that s usually bei...
1        winstonsalem nc reuters  civil rights groups a...
2        when loretta lynch was confirmed as the new di...
3        new york reuters  french farright presidential...
4        reuters  negotiators from canada mexico and th...
                               ...
44893    brasilia reuters  brazil s lower house of cong...
44894    mexico city reuters  tears flowed at our lady ...
44895    washington reuters  the white house on friday ...
44896    there has been a consistent thread in zionism ...
44897    no word yet on plans to defund state departmen...
Name: text, Length: 44898, dtype: object

In [132]:
y

0        0
1        1
2        0
3        1
4        1
        ..
44893    1
44894    1
44895    1
44896    0
44897    0
Name: label, Length: 44898, dtype: int64

In [133]:
from sklearn.model_selection import train_test_split

In [134]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [135]:
x_train.shape

(31428,)

In [136]:
x_test.shape

(13470,)

In [137]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [138]:
vectorization=TfidfVectorizer()

In [139]:
xv_train=vectorization.fit_transform(x_train)

In [140]:
xv_test=vectorization.transform(x_test)

In [141]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6429553 stored elements and shape (31428, 173814)>

In [142]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2749721 stored elements and shape (13470, 173814)>

In [143]:
from sklearn.linear_model import LogisticRegression

In [144]:
LR=LogisticRegression()

In [145]:
LR.fit(xv_train,y_train)

LogisticRegression()

In [146]:
pred_lr=LR.predict(xv_test)

In [147]:
LR.score(xv_test,y_test)

0.9880475129918337

In [148]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7076
           1       0.98      0.99      0.99      6394

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [149]:
from sklearn.tree import DecisionTreeClassifier

In [150]:
DTC =DecisionTreeClassifier()

In [151]:
DTC.fit(xv_train,y_train)

DecisionTreeClassifier()

In [152]:
pred_dtc=DTC.predict(xv_test)

In [153]:
DTC.score(xv_test,y_test)

0.9961395694135116

In [154]:
print(classification_report(y_test,pred_dtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7076
           1       1.00      1.00      1.00      6394

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [155]:
from sklearn.ensemble import RandomForestClassifier

In [156]:
rfc=RandomForestClassifier()

In [157]:
rfc.fit(xv_train,y_train)

RandomForestClassifier()

In [158]:
predict_rfc=rfc.predict(xv_test)

In [159]:
rfc.score(xv_test,y_test)

0.9879732739420936

In [160]:
print(classification_report(y_test,predict_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7076
           1       0.98      0.99      0.99      6394

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [161]:
from sklearn.ensemble import GradientBoostingClassifier

In [162]:
gbc=GradientBoostingClassifier()

In [163]:
gbc.fit(xv_train,y_train)

GradientBoostingClassifier()

In [164]:
pred_gbc=gbc.predict(xv_test)

In [165]:
gbc.score(xv_test,y_test)

0.9953971789161099

In [166]:
print(classification_report(y_test,pred_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7076
           1       0.99      1.00      1.00      6394

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [167]:
def output_label(n):
  if n==0:
    return "It is a Fake News "
  elif n==1:
    return "It is a Genuine News"

In [168]:
def manual_testing(news):
  testing_news={"text":[news]}
  new_def_test=pd.DataFrame(testing_news)
  new_def_test["text"]=new_def_test["text"].apply(wordopt)
  new_x_test=new_def_test["text"]
  new_xv_test=vectorization.transform(new_x_test)
  pred_lr=LR.predict(new_xv_test)
  pred_dtc=DTC.predict(new_xv_test)
  pred_rfc=rfc.predict(new_xv_test)
  pred_gbc=gbc.predict(new_xv_test)
  return print("\n\nLR Prediction: {} \nDT Prediction: {} \nRFC Prediction: {} \nGBC Prediction: {}".format(
      output_label(pred_lr[0]),output_label(pred_dtc[0]),output_label(pred_gbc[0]),output_label(pred_rfc[0])))

In [183]:
news_article=str(input())

WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a â€œfiscal conservativeâ€ on Sunday and urged budget restraint in 2018. In keeping with a sharp pivot under way among Republicans, U.S. Representative Mark Meadows, speaking on CBSâ€™ â€œFace the Nation,â€ drew a hard line on federal spending, which lawmakers are bracing to do battle over in January. When they return from the holidays on Wednesday, lawmakers will begin trying to pass a federal budget in a fight likely to be linked to other issues, such as immigration policy, even as the November congressional election campaigns approach in which Republicans will seek to keep control of Congress. President Donald Trump and his Republicans want a big budget increase in military spending, while Democrats also want proportional increases for non-defense â€œdiscretionaryâ€ spending on programs that support education, scientific research, infrastructure, public health and environmental protection. â€œThe (Trump) administration has already been willing to say: â€˜Weâ€™re going to increase non-defense discretionary spending ... by about 7 percent,â€™â€ Meadows, chairman of the small but influential House Freedom Caucus, said on the program. â€œNow, Democrats are saying thatâ€™s not enough, we need to give the government a pay raise of 10 to 11 percent. For a fiscal conservative, I donâ€™t see where the rationale is. ... Eventually you run out of other peopleâ€™s money,â€ he said. Meadows was among Republicans who voted in late December for their partyâ€™s debt-financed tax overhaul, which is expected to balloon the federal budget deficit and add about $1.5 trillion over 10 years to the $20 trillion national debt. â€œItâ€™s interesting to hear Mark talk about fiscal responsibility,â€ Democratic U.S. Representative Joseph Crowley said on CBS. Crowley said the Republican tax bill would require the  United States to borrow $1.5 trillion, to be paid off by future generations, to finance tax cuts for corporations and the rich. â€œThis is one of the least ... fiscally responsible bills weâ€™ve ever seen passed in the history of the House of Representatives. I think weâ€™re going to be paying for this for many, many years to come,â€ Crowley said. Republicans insist the tax package, the biggest U.S. tax overhaul in more than 30 years,  will boost the economy and job growth. House Speaker Paul Ryan, who also supported the tax bill, recently went further than Meadows, making clear in a radio interview that welfare or â€œentitlement reform,â€ as the party often calls it, would be a top Republican priority in 2018. In Republican parlance, â€œentitlementâ€ programs mean food stamps, housing assistance, Medicare and Medicaid health insurance for the elderly, poor and disabled, as well as other programs created by Washington to assist the needy. Democrats seized on Ryanâ€™s early December remarks, saying they showed Republicans would try to pay for their tax overhaul by seeking spending cuts for social programs. But the goals of House Republicans may have to take a back seat to the Senate, where the votes of some Democrats will be needed to approve a budget and prevent a government shutdown. Democrats will use their leverage in the Senate, which Republicans narrowly control, to defend both discretionary non-defense programs and social spending, while tackling the issue of the â€œDreamers,â€ people brought illegally to the country as children. Trump in September put a March 2018 expiration date on the Deferred Action for Childhood Arrivals, or DACA, program, which protects the young immigrants from deportation and provides them with work permits. The president has said in recent Twitter messages he wants funding for his proposed Mexican border wall and other immigration law changes in exchange for agreeing to help the Dreamers. Representative Debbie Dingell told CBS she did not favor linking that issue to other policy objectives, such as wall funding. â€œWe need to do DACA clean,â€ she said.  On Wednesday, Trump aides will meet with congressional leaders to discuss those issues. That will be followed by a weekend of strategy sessions for Trump and Republican leaders on Jan. 6 and 7, the White House said. Trump was also scheduled to meet on Sunday with Florida Republican Governor Rick Scott, who wants more emergency aid. The House has passed an $81 billion aid package after hurricanes in Florida, Texas and Puerto Rico, and wildfires in California. The package far exceeded the $44 billion requested by the Trump administration. The Senate has not yet voted on the aid.

In [184]:
manual_testing(news_article)

LR Prediction: It is a Genuine News
DT Prediction: It is a Genuine News
RFC Prediction: It is a Genuine News
GBC Prediction: It is a Genuine News